name: mb_report
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf


  uses-material-design: true

  assets:
    - images/flashcard logo.png
    - images/Mobile App Logo.png
    - images/headerLogo.svg
    - images/user-profile.png
    - images/ben-user-profile.jpg
    - images/baby-girl.png
    - images/birthday.jpeg
    - images/pet-birthday.jpeg
    - images/all_about_halloween.jpeg

